project:
  type: website

website:
  title: "Package"
  cookie-consent:
    type: express
  navbar:
    left:
      - fn-stats.qmd
      - github.qmd
    right:
      - icon: "github"
        menu:
          - text: Source Code
            url: https://github.com/ropensci-review-tools/repometrics
          - text: Request a Feature
            url: https://github.com/ropensci-review-tools/repometrics/issues/new

format:
  html:
    theme: cosmo
    toc: true
