---
title: "Historical Data"
execute:
  echo: false
format: 
  html:
    fig-width: 8
    fig-height: 4
    code-fold: false
---

```{r load-pkg, echo = FALSE, message = FALSE}
library (githist)
library (lubridate)
```
This page includes several graphs providing insight into the historical
development of ...

```{r load-data}
dat <- readRDS ("results.Rds")
```
```{r stats-data}
cols <- names (dat$stats) [which (!names (dat$stats) %in% c ("package", "version"))]
stats <- dat$stats [, cols]
stats$date <- lubridate::ymd (strftime (stats$date, "%y-%m-%d"))
index <- which (stats$measure == "sum")
stats$npars [index] <- stats$npars [index] / 100
stats$loc [index] <- stats$loc [index] / 100
stats$ext_calls [index] <- stats$ext_calls [index] / 20

stats <- tidyr::pivot_longer (stats, c ("doclines", "npars", "loc", "ext_calls"))
```

```{r ojs-in-stats, echo = FALSE}
ojs_define (stats_in = stats)
```
```{ojs stats-transpose}
stats = {
    return transpose(stats_in).map(row => ({
        ...row,
        date: new Date(row.date)
    }));
}
viewof name = Inputs.radio(
    ["doclines", "npars", "loc", "ext_calls"],
    {
        value: "npars",
        label: "Variable:",
    }
)
statsFiltered = stats.filter(function(row) {
  return name.includes(row.name)
})
```

```{ojs stats-plot}
Plot.plot({
    style: `
        overflow: visible;
    `,
    marginLeft: 60,
    marginBottom: 50,
    x: {grid: true},
    y: {grid: true},
    marks: [
        Plot.ruleY([0]),
        Plot.lineY(
            statsFiltered,
            {
                x: "date",
                y: "value",
                stroke: "measure",
                fontSize: 18
            }
        ),
        Plot.axisX(
            {
                fontSize: 14,
                label: "",
                labelArrow: false
            }
        ),
        Plot.axisX(
            {
                fontSize: 20,
                label: "Date",
                labelAnchor: "center",
                labelOffset: 40,
                ticks: []
            }
        ),
        Plot.axisY(
            {
                fontSize: 14,
                label: "",
                labelArrow: false
            }
        ),
        Plot.axisY(
            {
                fontSize: 24,
                label: "Value",
                labelAnchor: "center",
                labelOffset: 55,
                ticks: []
            }
        ),
    ]
})
```
